# Generated by Django 4.0 on 2022-03-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ltext',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='autor',
            new_name='author',
        ),
    ]
